 memory write::    2->M(   7)
  At end of instruction 1
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4    5    7    3    8    7    0    3    0 2019    7    2  750 0000 
 memory write:: FFFB->M(   5)
  At end of instruction 2
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4    5    7    4    2 FFFB    7    5 FFFB    2    5 FFFB 2019 1001 
