  At end of instruction 1
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     1    5    6    1    0    1    0    0    1    0    0  200  200 0000 
  At end of instruction 2
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     1    5    6    3    0    3    0    0    1    0    1   91   91 0000 
  At end of instruction 3
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     1    5    7    4    1    7    1    6    7    6    3 1002 1002 0000 
